import "./globals.css";
import { Inter } from "next/font/google";
import Navigation from "@/components/general/navigation/Navigation";
import Footer from "@/components/general/Footer";
import { ThemeProvider } from "next-themes";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head />
			<body className={`${inter.className} dark:bg-black bg-white`}>
				<ThemeProvider defaultTheme="system" attribute="class">
					<main>
						<Navigation />
						{children}
					</main>
					<footer>
						<Footer />
					</footer>
				</ThemeProvider>
			</body>
		</html>
	);
}
